apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: restic-snapshot
  namespace: demo
spec:
  volumeSnapshotClassName: topolvm-online
  source:
    persistentVolumeClaimName: demo-pvc